### ISSUE TITLE
CI/CD: Improve builds/releases pipeline

### ISSUE THREAD

**Issue by yveszoundi** [rimerosolutions/entrusted#75]
#### Background

Since `0.3.1`, releases artifacts are assemble via the GitHub infrastructure (GitHub Actions), instead of using a local Ubuntu virtual machine. Please note that few pre-existing shell scripts are also reused in GitHub actions.

#### Problems

Existing shell scripts were built with an emphasis on supporting multiple architectures quickly (x86_64 and arm64)

- It can take lots of effort to support people experiencing local builds challenges for multiple reasons
- The way that scripts were initially assembled (and rationale behind it) can be frustrating when build errors arise
- The fact that local builds are only tested under an Ubuntu virtual machine; Supporting all kinds of users with their Linux distributions isn't possible
- Some configurations/decisions might require specific Linux or tooling knowledge
- Some other things just "suck" and didn't get refactored yet

#### Tasks

On top of items below, it would be nice to come closer to "reproducible builds" (containerized builds only help with parts of that).

- [x] Review existing shell scripts
   - [x] Evaluate opportunities to simplify logic
   - [x] Review error handling and retries
   - [x] Evaluate opportunities to make builds more flexible
   - [x] Move scripting logic inside containers as much as possible
- [x] Review container builder images default programs
  - [x] Evaluate opportunities to trim container size
  - [x] Remove duplicate or unrequired commands (symlinks, etc.)

**Comment by yveszoundi** [comment]
See also https://github.com/rimerosolutions/entrusted/issues/79
